version: "3.2"
services:

  # minimal container that builds the ratelimit service binary and exits.
  ratelimit-build:
    image: golang:1.14
    working_dir: /go/src/github.com/envoyproxy/ratelimit
    command: go build -o /usr/local/bin/ratelimit ./src/service_cmd/main.go
    volumes:
      - .:/go/src/github.com/envoyproxy/ratelimit
      - type: bind
        source: ./runtime/bin/
        target: /usr/local/bin/
        read_only: false
    environment:
      - GOPROXY=https://mirrors.aliyun.com/goproxy/

  ratelimit-client-build:
    image: golang:1.14
    working_dir: /go/src/github.com/envoyproxy/ratelimit
    command: go build -o /usr/local/bin/ratelimit_client ./src/client_cmd/main.go
    volumes:
      - .:/go/src/github.com/envoyproxy/ratelimit
      - type: bind
        source: ./runtime/bin/
        target: /usr/local/bin/
        read_only: false
    environment:
      - GOPROXY=https://mirrors.aliyun.com/goproxy/

